### ISSUE TITLE
remind implementors of the "fun" parts of no flow control

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/datagram#1]
Flow control is painful because getting it wrong is painful.

Not having flow control doesn't mean having it done right!

Would be great to have a brief reminder around this in the draft!

(Issue copied from [individual draft repo](https://github.com/tfpauly/draft-pauly-quic-datagram/issues/33), by @grmocg on 2019-11-19)

**Comment by tfpauly** [comment]
I expect this may be covered when we add text for #15

**Comment by tfpauly** [comment]
I believe this should be covered sufficiently now with the current text. Please open a this or a new issue if you disagree!
