### ISSUE TITLE
Question about scope: why only unreliable datagrams? Why not reliable datagrams too?

### ISSUE THREAD

**Issue by skissane** [quicwg/datagram#12]
Some applications might want to send messages, and not care about the order of delivery, but still get reliability.

QUIC streams give them reliability, but within a stream it enforces order of delivery.

This datagram proposal gives unordered delivery of messages, but without reliability.

Why not provide datagrams with optional (opt-in) reliability?

It shouldn't be a lot of extra work for QUIC implementors to provide reliable datagrams as well as unreliable, given that retransmission is already there for QUIC streams.

(I guess an application could create a separate QUIC stream for each unordered reliable message. That might work, but seems ugly and may have some overhead.)

**Comment by DavidSchinazi** [comment]
What you describe can already be accomplished using streams: each “reliable datagram” is its own stream. That provides reliable delivery without ordering between independent datagrams. I don’t think we need to add optional reliability to the datagram spec.

**Comment by Ralith** [comment]
> I guess an application could create a separate QUIC stream for each unordered reliable message. That might work, but seems ugly and may have some overhead

Streams are very lightweight, and well suited to this task. Beware applying intuition from TCP too heavily.

**Comment by skissane** [comment]
So, here's a suggestion then: since I'm sure I'm not the only person who is going to think of this, maybe add some verbiage to the spec explaining why supporting reliable datagrams is unnecessary?

**Comment by DavidSchinazi** [comment]
Sounds good. We can keep this issue open as requesting an editorial change.
