### ISSUE TITLE
Why is the recommended `max_datagram_frame_size` 65536?

### ISSUE THREAD

**Issue by tfpauly** [quicwg/datagram#13]
Current text says:

> It is RECOMMENDED to send the value 65536 in the max_datagram_frame_size transport parameter as that indicates to the peer that this endpoint will accept any DATAGRAM frame that fits inside a QUIC packet.

This is nice, but I'm wondering if it should be 65535. The max UDP payload for a QUIC packet is 65527, which is lower than both. It's nice for an implementation to only need to store 16-bit integers for max datagram size to avoid excess memory, and it's of course easy to round down from 65536 to 65535, but it just seems arbitrary to have it be 1 more than the max value for a 16-bit integer...

**Comment by tfpauly** [comment]
@DavidSchinazi  thoughts?

**Comment by DavidSchinazi** [comment]
That sounds reasonable, 65535 is fine by me. (as long as the 1s don't take longer to travel than the 0s 🤣)
