### ISSUE TITLE
Document interaction of datagrams with pacing

### ISSUE THREAD

**Issue by vasilvv** [quicwg/datagram#16]
Early in our VPN implementation, we sent QUIC datagrams without any queueing, assuming that if a datagram gets dropped, then we exceeded the cwnd (and thus the estimated channel capacity), so it would likely not reach the peer anyways.  In practice, this turned out to be a terrible idea that lead to underutilization of the channel; our implementation always does pacing, so if you don't queue the datagram, it *will* get dropped unless it just happens to fit into the current pacing quantum.

Because pacing is RECOMMENDED for QUIC, I believe some form of queueing should be RECOMMENDED for datagrams, otherwise the users risk running into the same hard-to-debug problem that we had.

**Comment by DavidSchinazi** [comment]
I think adding a note about pacing to the "Congestion Control" subsection makes sense to me.

**Comment by ekinnear** [comment]
+1, if you're in the bucket of implementations that have insight into their pacing algorithm, it should be reasonable to expect that you'd avoid dropping your own datagrams unless you make a queue and then build up too much in that queue.
