### ISSUE TITLE
Lack of application-defined format

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/datagram#35]
Neither this draft nor H3-Datagrams says what the behavior should be when the transport supports DATAGRAM frames but no supported application format has been negotiated for them.  While I think the correct behavior would be to drop them, since there's no ability to interpret their payload, no document actually says that.  There's also a legitimate argument for closing the connection, since something was sent that the application layer can't deal with.

H3-Datagrams probably can't say that, since the possibility exists that a different datagram-payload format will be deployed for HTTP/3 in the future.  Should this document have a sentence about what happens when the application-layer doesn't define what to do with incoming datagrams / doesn't consume them?

(There's also the question of simultaneously supporting two different formats, but I think that's an application-layer issue this document can ignore.)

**Comment by DavidSchinazi** [comment]
Due to reordering, it's possible that a DATAGRAM frame arrives before the QUIC packet which negotiates the application format. Therefore we can't close the connection here. Depending on the application, it might be best to drop the datagram, or buffer it in hopes of later negotiating the format. I'm not sure draft-ietf-quic-datagram needs to say anything, what's wrong with leaving that up to applications?

**Comment by LPardue** [comment]
The corollary to Mike's question also applies, what happens if an application protocol doesn't use QUIC streams?

Getting something written somewhere seems sensible, I suggest the applicability draft.

**Comment by MikeBishop** [comment]
True, there's also an indeterminate state before you know what the application supports, for H3 at least.  But once you know what the application supports and behavior is different than expected, something needs to happen. Preferably there should be a spec that says what should happen; implementation guidance in applicability is an option as well.

**Comment by tfpauly** [comment]
I don't think there's anything concrete the transport can say here, but we could point to the fact that the application needs to define it's behavior for datagrams.

**Comment by tfpauly** [comment]
Sense of the room in 111 was that we should probably close this with no action.
