### ISSUE TITLE
Instances of lowercase "may" 

### ISSUE THREAD

**Issue by LPardue** [quicwg/datagram#4]
There are several instances of lowercase "may" in this document. It is ambiguous if these are normative requirements or not.

**Comment by DavidSchinazi** [comment]
Could you elaborate on why it's ambiguous? We have a reference to RFC 8174.

**Comment by LPardue** [comment]
I sometimes assume typos :) If you're happy the present document is correct, I will close this issue

**Comment by DavidSchinazi** [comment]
I'm not aware of errors like this, do you have any specific ones in mind?

**Comment by LPardue** [comment]
Gah, fat fingered accidental close.

The example that triggered opening this issue is below, I had to read this several times. Perhaps that's just a sign that editorial tweaks would help, regardless of the exact words in use

> The risk associated with not providing flow control for DATAGRAM frames is that a receiver may not be able to commit the necessary resources to process the frames. For example, it may not be able to store the frame contents in memory. However, since DATAGRAM frames are inherently unreliable, they MAY be dropped by the receiver if the receiver cannot process them.

**Comment by tfpauly** [comment]
I can fix this
