### ISSUE TITLE
Is it obvious that Datagram frame can be aggregated in the same QUIC packet

### ISSUE THREAD

**Issue by gloinul** [quicwg/datagram#41]
I find no discussion about aggregating DATAGRAM frames in the same QUIC packets, with other DATAGRAM frames or other types. Is that so obvious that it is possible that it doesn't need mentioning?

I would be slightly worried that an QUIC stack that aggregate may cause fate sharing between different datagram frames, which the application wasn't expecting. In a classical UDP application clearly doing two calls for UDP packets will create two different packets. Two calls to transmit Datagram frames may not cause multiple QUIC packets to be sent, which is usually for the good. However, it goes back to maybe be clear that this may occurr, and a question if API needs consideration to indicate if aggregation is fine or not?

**Comment by DavidSchinazi** [comment]
We originally had text for this, but folks pointed out that we can't make recommendations that apply to all use cases: some might want fate sharing while some might not. It's probably best to leave this up to the application.

**Comment by gloinul** [comment]
So I don't think recommendations are necessary. I think bringing up the issue and the potential need for an API to indicate on per datagram if it is okay for this to be aggregated with other datagrams would be sufficient.

**Comment by tfpauly** [comment]
Hm, I don't know if there needs to an API for this, that seems like an implementation-specific decision. I'd prefer to not add text for this, to let the applications that use datagrams be free in their usage.

That's not saying that HTTP/3, CONNECT-UDP, can't make recommendations, just that it doesn't need to belong here.

**Comment by LPardue** [comment]
Section 5 and 5.1 mention the frame can be coalesced with other frames in a packet, and some of the multiplexing concerns. That seems like enough to me.

The suggestion for a specific API to mark non-coalescing reminds me of an issue I opened (and closed) a year ago - https://github.com/quicwg/datagram/issues/5. 

I think the text in 5.1 is already open enough to allow people to support this capability as part of a "prioritization API" if they wanted, saying anything more specific seems subjective and implementation territory - as David and Tommy have said.

@gloinul I'd like to wrap this issue up and I'm not seeing much for the editors to do. Can we close it or do you have some specific proposal?

**Comment by tfpauly** [comment]
@gloinul are you okay to close this issue?

**Comment by gloinul** [comment]
Yes you may close this issue. I think what is in the editors copy are sufficient.
