### ISSUE TITLE
Can DATAGRAM frame belong to stream?

### ISSUE THREAD

**Issue by wangweiwei1188** [quicwg/datagram#51]
The draft-ietf-quic-datagram has the following words: DATAGRAM frames belong to a QUIC connection as a whole, and are not strongly associated with any stream ID at the QUIC layer.
Can DATAGRAM belong to stream?  And one stream has two type: one for unreliable transmission(DATAGRAM FRAME) and another one for reliable transmission(STREAM FRAME).

**Comment by DavidSchinazi** [comment]
At the QUIC layer, datagrams don't belong to streams. In HTTP/3 however, datagrams are associated with streams - see [draft-ietf-masque-h3-datagram](https://datatracker.ietf.org/doc/html/draft-ietf-masque-h3-datagram) for details.

**Comment by wangweiwei1188** [comment]
OK, Thanks.
