### ISSUE TITLE
Question about DATAGRAM frame

### ISSUE THREAD

**Issue by wangweiwei1188** [quicwg/datagram#54]
The draft has the following words:
This document defines two new DATAGRAM QUIC frame types, which carry application data without requiring retransmissions.

The draft don't describe it like:When DATAGRAM frame is lost, the implemention  should not retransmission it.That's to say, when DATAGRAM  frame's lost, the implemention have two strategy，one for retransmissing, another for not.That's right?

**Comment by tfpauly** [comment]
DATAGRAM frames are never retransmitted. The reason there are technically two frame types is that there’s a version that includes it’s length, and a version that just extends to the end of the packet. That’s just like STREAM frames.

Does this answer your question @wangweiwei1188 ?

**Comment by wangweiwei1188** [comment]
Yeah, Thanks.
