### ISSUE TITLE
Is reliability really stream-based?

### ISSUE THREAD

**Issue by martinduke** [quicwg/datagram#56]
In the introduction, it says
"Reliability within QUIC is performed on a per-stream basis, so some frame types are not eligible for retransmission"

Is it really per-stream? Some frames are retransmitted even though they aren't associated with a stream.

Really, the detection mechanism is packet-based, the retransmission decision is made on a per-frame basis, and for stream-specific frames there is the added consideration of stream state (i.e. do not resend if reset)

I suggest replacing the sentence above with "Some QUIC frame types are not eligible for retransmission."

**Comment by DavidSchinazi** [comment]
> In the introduction, it says
> "Reliability within QUIC is performed on a per-stream basis, so some frame types are not eligible for retransmission"
> 
> Is it really per-stream? Some frames are retransmitted even though they aren't associated with a stream.

Do you have examples? It's common for an action to be attempted again, but not for the frame to be retransmitted.

> Really, the detection mechanism is packet-based, the retransmission decision is made on a per-frame basis, and for stream-specific frames there is the added consideration of stream state (i.e. do not resend if reset)

That's not quite right. QUIC does not retransmit stream frames, it instead looks at stream state to see what data needs to be retransmitted - there's an important conceptual difference there: let's say you had 100 bytes left in your packet and therefore sent 98 bytes of stream data and that got lost but now you have a full 1200 payload available, you shouldn't retransmit that 100 byte STREAM frame and instead create a new STREAM frame with as much data as you want to send.

[RFC 9000 s2.2](https://datatracker.ietf.org/doc/html/rfc9000#section-2.2) states:
> Streams are an ordered byte-stream abstraction with no other structure visible to QUIC.  STREAM frame boundaries are not expected to be preserved when data is transmitted, retransmitted after packet loss, or delivered to the application at a receiver.

**Comment by martinduke** [comment]
So I agree with everything you're saying factually; this is an editorial, semantic gripe about what it means that reliability is on a per-stream basis and what it means that a frame is retransmitted.

It's true that, for example, MAX_DATA frames aren't resent verbatim, but RFC 9000 addresses them in a section called "retransmission of information" due to the common-sense meaning of the term.

What are you trying to communicate by saying that reliability is "on a per-stream basis"?

**Comment by DavidSchinazi** [comment]
I agree that this sentence is confusing. Perhaps we just remove it entirely? @tfpauly @ekinnear thoughts?

**Comment by tfpauly** [comment]
@DavidSchinazi @martinduke made a proposal with #58
