### ISSUE TITLE
State clearly the IANA registration type of TP and frame type

### ISSUE THREAD

**Issue by LPardue** [quicwg/datagram#59]
Noticed during the shepherd writeup of IANA considerations:

The document is attempting to register:

- max_datagram_frame_size Transport Parameter with value 0x0020
- DATAGRAM frame type with values 0x30 and 0x31

According to IANA (https://www.iana.org/assignments/quic/quic.xhtml) registrations can be of different types. Here the requested values are in the `permanent, 0x00-0x3f | Standards Action or IESG Approval` bracket. 

So I suggest that the document state clearly that this is a request for permanent registration of these types.

**Comment by DavidSchinazi** [comment]
Agreed. Wrote up #60 to fix this.
