### ISSUE TITLE
Why do IANA considerations duplicate information from the body?

### ISSUE THREAD

**Issue by LPardue** [quicwg/datagram#61]
Noticed during Shepherd review.

All of the core types registered in RFC 9000 simply link to the relevant document (RFC 9000) and section in the document where the protocol element is defined. 

In contrast, in datagram's IANA considerations section, the transport parameter and frame type registrations include the required `specification` field with some text that is already included in the document. This will manifest as a weird juxtaposition in the IANA table.

I suggest you simply reference the section 3 and section 4 respectively. If you really want some prose (I don't recommend that) then it can be added as a note to the table.

**Comment by DavidSchinazi** [comment]
I noticed that when writing #60 and I agree, we should just list "This specification" in there as most RFCs do.
