### ISSUE TITLE
consequence of not protecting DATAGRAM with 0-RTT or 1-RTT

### ISSUE THREAD

**Issue by zaheduzzaman** [quicwg/datagram#65]
Section 5: says

DATAGRAM frames MUST be protected with either 0-RTT or 1-RTT keys.

I would suggest to add the "otherwise what happens" part. One/two like explanation will be helpful and I think that will improve the understanding of this requirement.

**Comment by tfpauly** [comment]
Almost all QUIC frame types are like this. I would suggest saying "Like STREAM frames, ..." to make this obvious for the rationale.
