### ISSUE TITLE
Text on Datagram's Interaction with Loss Recovery is a bit Light

### ISSUE THREAD

**Issue by nibanks** [quicwg/datagram#8]
The draft has some good text in the "Acknowledgement Handling" and "Congestion Control" sections that essentially is stating that DATAGRAM is just like any other ACK-eliciting packet, but is not automatically retransmitted by the transport. That's all reasonable, but I think there needs to be more text on how the (suspected) loss of a packet with a DATAGRAM frame or a PTO with only an outstanding DATAGRAM packet should be handled.

I can see two possible models:

1. It's just like any other packet. The goal is to elicit some ACK from the peer to get accurate loss information about the outstanding packet as soon as possible. If there is nothing outstanding we could use to send in a new packet, just send a PING frame.

2. It's special. Because we don't necessarily intend to retransmit the data in the packet if it is actually lost, we don't actually care about immediate loss information/feedback. Don't force anything to be sent immediately to elicit the ACK.

So far as I have it coded up in MsQuic, I've assumed (1). This essentially results in an immediate PING frame/packet being sent out if I have nothing else to retransmit to try to elicit an ACK for the DATAGRAM frame/packet. This could result in a slightly noisier connection if the app doesn't care about all loss information about their datagrams, but, IMO makes for a cleaner design. I don't know what the general consequences to congestion control might be if we don't do this.

Assuming folks are in agreement, we should have some text on this topic in the draft.

**Comment by DavidSchinazi** [comment]
@ianswett @janaiyengar as authors of the recovery draft do you have an opinion here?

**Comment by ianswett** [comment]
I support @nibanks choice of 1 and it aligns with the recovery draft.  It also matches our implementation. 

Adding clarifying text around this SG and I'd be happy to review it.

**Comment by janaiyengar** [comment]
I agree -- choice (1) is cleanest and I would argue that choice(2) is really not principled.

**Comment by MikeBishop** [comment]
Late to the issue, but I think (1) is the right choice here.  It's not simply that datagrams aren't retransmitted, but that they _might_ be retransmitted by the application if they're declared lost.  If you don't have prompt feedback, that scenario suffers.

**Comment by tfpauly** [comment]
Seems like we have good agreement on this, just need to write the text

**Comment by janaiyengar** [comment]
@tfpauly -- To @ianswett 's comment at the mic, you should cite [Section 6.2.4 in the recovery draft](https://quicwg.org/base-drafts/draft-ietf-quic-recovery.html#section-6.2.4).
