### ISSUE TITLE
RFC Editor comment 2

### ISSUE THREAD

**Issue by LPardue** [quicwg/datagram#82]
Please review whether the "type" attribute should be set for
the sourcecode element in the XML file. If the current list of preferred
values for "type"
(https://www.rfc-editor.org/materials/sourcecode-types.txt) does not
contain an applicable type, then feel free to suggest a new one.
Also, it is acceptable to leave the "type" attribute not set.

**Comment by tfpauly** [comment]
Looking at RFC 9000, these aren't source code, but are artwork, and without a type:

```
          <artwork name="" type="" align="left" alt="" pn="section-19.8-5.1">
STREAM Frame {
  Type (i) = 0x08..0x0f,
  Stream ID (i),
  [Offset (i)],
  [Length (i)],
  Stream Data (..),
}
</artwork>
```

I'd suggest matching that.

**Comment by DavidSchinazi** [comment]
Matching RFC9000 SGTM
