### ISSUE TITLE
For clarity, may this sentence be updated as follows?

Original (comment 3)

### ISSUE THREAD

**Issue by LPardue** [quicwg/datagram#83]
For clarity, may this sentence be updated as follows?

Original:

       Identifiers used to multiplex different kinds of datagrams, or flows
       of datagrams, are the responsibility of the application protocol
       running over QUIC to define.  

Perhaps:
   Defining the identifiers used to multiplex different kinds of
   datagrams or flows of datagrams is the responsibility of the
   application protocol running over QUIC.

**Comment by DavidSchinazi** [comment]
SGTM

**Comment by tfpauly** [comment]
Agreed, this looks fine to me.
