### ISSUE TITLE
Would you like to change "and" to "-" here?

Current (comment 4)

### ISSUE THREAD

**Issue by LPardue** [quicwg/datagram#84]
Would you like to change "and" to "-" here?

Current: 0x30 and 0x31
Perhaps: 0x30-0x31

The latter would match the IANA registry and would
match how 0x12-0x13 (for example) appears in RFC 9000
(https://www.rfc-editor.org/rfc/rfc9000.html#section-12.4).

**Comment by tfpauly** [comment]
Yes, we should change this to match the IANA registry

**Comment by DavidSchinazi** [comment]
SGTM
