### ISSUE TITLE
Nit picking error condition for supported but not enabled

### ISSUE THREAD

**Issue by LPardue** [quicwg/datagram#9]
Sorry/not sorry for being pernickety. The current draft says:

```
An endpoint that includes this parameter supports the DATAGRAM frame types and is willing to receive such frames on this connection.
```

and

```
An endpoint that receives a DATAGRAM frame when it has not sent the max_datagram_frame_size transport parameter MUST terminate the connection with error PROTOCOL_VIOLATION.
```

which is slightly ambiguous if we consider an vanilla QUIC endpoint that does not implement this extension at all. Absence of the TP can indicate the parameter is totally unsupported, or is supported but is not desired for the current connection.  In the totally unsupported case, the receiving endpoint is likely to act according to transport Section 12.4 which says

```
An endpoint MUST treat the receipt of a frame of unknown type as a
connection error of type FRAME_ENCODING_ERROR.
```

Maybe this doesn't need to be fixed because one shouldn't expect the requirements of an extension to apply if it is not implemented. But perhaps some editorial tweaks could tighten things up.

For the case of an endpoint does support DATAGRAM. You might also want to consider a wire message that more clearly describes the error condition of "extension supported but not enabled". This could be a new error code, or a reason phrase.

**Comment by nibanks** [comment]
It does seem to make sense to just to follow the guidance from the transport draft and use `FRAME_ENCODING_ERROR`. If folks want to add a reason phrase too, feel free, but that seems to be a implementation decision to me.

**Comment by LPardue** [comment]
The problem with reusing `FRAME_ENCODING_ERROR` is then it is completely ambiguous if the endpoint supports the extension but didn't enable it, or the endpoint doesn't support the extension at all. To me there is value in using different error codes for those conditions (we can't rely on endpoints populating or recording the reason phrase, as you say). The issue with `PROTOCOL_ERROR` is that it is different to `FRAME_ENCODING_ERROR` but is also the catch all bucket.

**Comment by DavidSchinazi** [comment]
I'm not sure I understand this issue. If a QUIC implementation does not support this specification, it is not bound by any of the requirements in this specification. So it'll happily use `FRAME_ENCODING_ERROR`.

This specification defines an extension to QUIC, and it can supersede any normative text in the QUIC specs. Therefore, if an implementation supports this extension, then it'll send `PROTOCOL_VIOLATION`.

I don't see any ambiguity here.

**Comment by LPardue** [comment]
I still see it but I think it all degenerates to "we can't protect against stupid" and that a more specific error code likely won't help a dumb client that sends DATAGRAMs in spite of not receiving the required TP. The strong signal of connection close is probably good enough, so let's close this and revisit if interop so reveals it to be useful.
